
[workspace]
members = [
    "lidarserv-server",
    "lidarserv-common",
    "lidarserv-viewer",
    "input-file-replay",
    "output-file-query",
    "point-cloud-viewer",
    "experiments",
    "evaluation",
    "default-functions-derive"
]
resolver = "2"
