
[workspace]
members = [
    "lidarserv-server",
    "lidarserv-common",
    "lidarserv-viewer",
    "input-file-replay",
    "output-file-query",
    "point-cloud-viewer",
    "evaluation", 
    "input-ros"
]
resolver = "2"
