
[workspace]
members = [
    "lidarserv-server",
    "lidarserv-common",
    "lidarserv-viewer",
    "velodyne-csv-replay",
    "point-cloud-viewer",
    "experiments",
    "evaluation",
    "default-functions-derive"
]
