data_folder = "data/evaluation"
output_file = "evaluation/results/2023-08-20_insertion_speed_comparison/insertion_speed_v1_%d_%i.json"
points_file = "data/frankfurt_street.las"
trajectory_file = ""
offset = [0,0,0]
las_point_record_format = 3
enable_cooldown = true
indexing_timeout_seconds = 86400 # one day
use_existing_index = false


[defaults]
type = "Octree"
priority_function = "TaskAge"
num_threads = 10
cache_size = 5000
node_hierarchy = 16
point_hierarchy = 23
compression = false
nr_bogus_points = [0, 0] # keep it deactived here to prevent wrong results with queries
insertion_rate.target_point_pressure = 3_000_000
query_perf.enable = false
latency.enable = false
enable_attribute_index = false
enable_histogram_acceleration = false
bin_count_intensity = 25
bin_count_return_number = 8
bin_count_classification = 256
bin_count_scan_angle_rank = 25
bin_count_user_data = 25
bin_count_point_source_id = 25
bin_count_color = 25

[runs.compressed_no_attribute_index]
compression = [true]
enable_attribute_index = [false]

[runs.compressed_attribute_index]
compression = [true]
enable_attribute_index = [true]

[runs.compressed_histogram_index]
compression = [true]
enable_attribute_index = [true]
enable_histogram_acceleration = [true]

[runs.uncompressed_no_attribute_index]
compression = [false]
enable_attribute_index = [false]

[runs.uncompressed_attribute_index]
compression = [false]
enable_attribute_index = [true]

[runs.uncompressed_histogram_index]
compression = [false]
enable_attribute_index = [true]
enable_histogram_acceleration = [true]