data_folder = "data/evaluation"
output_file = "evaluation/results_2024/2024-01-09_query_performance/query_performance_v1_%d_%i.json"
points_file = "data/AHN4_66M.laz"
trajectory_file = ""
offset = [0,0,0]
las_point_record_format = 3
enable_cooldown = false
use_existing_index = false
indexing_timeout_seconds = 3000

[defaults]
type = "Octree"
priority_function = "TaskAge" #best = TaskAge
num_threads = 24
cache_size = 10000
compression = false
nr_bogus_points = [0, 0]
node_hierarchy = 17
point_hierarchy = 24
insertion_rate.target_point_pressure = 1_000_000
query_perf.enable = true
latency.enable = false
enable_attribute_index = true
enable_histogram_acceleration = true
bin_count_intensity = 25
bin_count_return_number = 8
bin_count_classification = 256
bin_count_scan_angle_rank = 25
bin_count_user_data = 25
bin_count_point_source_id = 256
bin_count_color = 25

[runs.test]