points_file = "../../../data/AHN4_66M.laz"
index_folder = "../../../data/evaluation"
output_file = "node_hierarchy_comparison_%d_%i.json"
use_existing_index = false
cooldown_seconds = 0
indexing_timeout_seconds = 200
target_point_pressure = 1_000_000
attributes = "LasPointFormat6Raw"

[queries]
lod0 = "lod(0)"
lod1 = "lod(1)"
#lod2 = "lod(2)"
#full-point-cloud = "full"

[coordinate_system]
scale = [
    0.001,
    0.001,
    0.001,
]
offset = [
    0.0,
    0.0,
    0.0,
]

[defaults]
node_hierarchy = 18
point_hierarchy = 11
priority_function = "NrPointsWeightedByTaskAge"
num_threads = 32
cache_size = 10000
compression = false
nr_bogus_points = [0, 0]
max_lod = 10
enable_attribute_index = false

[runs.n18p11]
node_hierarchy = [18]
point_hierarchy = [11]

[runs.n17p10]
node_hierarchy = [17]
point_hierarchy = [10]

[runs.n16p09]
node_hierarchy = [16]
point_hierarchy = [9]

[runs.n15p08]
node_hierarchy = [15]
point_hierarchy = [8]

[runs.n14p07]
node_hierarchy = [14]
point_hierarchy = [7]

[runs.n13p06]
node_hierarchy = [13]
point_hierarchy = [6]

[runs.n12p05]
node_hierarchy = [12]
point_hierarchy = [5]

[runs.n11p04]
node_hierarchy = [11]
point_hierarchy = [4]
