points_file = "../../../data/AHN4.las"
index_folder = "../../../data/ahn4-eval"
output_file = "ahn4_latency_%d_%i.json"
cooldown_seconds = 0
indexing_timeout_seconds = 50000
target_point_pressure = 1000000
attributes = "LasPointFormat1Raw"
# record length 34
#min x y z:                  96750.700 493750.000 -7.079
#max x y z:                  134999.999 512499.999 135.977
# Min GPS Time: 269521185.6002241
#Max GPS Time: 270204590.1666351

[queries]
full-point-cloud = "full"

[coordinate_system]
scale = [
    0.001,
    0.001,
    0.001,
]
offset = [
    0.0,
    0.0,
    0.0,
]

[indexed_attributes]
classification = [
    "RangeIndex",
    { SfcIndex = { nr_bins = 16 } },
]
intensity = ["RangeIndex"]
gpstime = ["RangeIndex"]

[defaults]
measure_query_latency = true
measure_index_speed = false
measure_query_speed = false
node_hierarchy = 25
point_hierarchy = 17
max_lod = 14
priority_function = "NrPointsWeightedByTaskAge"
num_threads = 32
cache_size = 10000
compression = false
nr_bogus_points = [
    0,
    0,
]
enable_attribute_index = true

[runs.main]
