points_file = "TODO"
index_folder = "TODO"
output_file = "hamburg_%d_%i.json"
use_existing_index = false
cooldown_seconds = 0
indexing_timeout_seconds = 50000
target_point_pressure = 1000000
attributes = "TODO"

[queries]

[coordinate_system]
scale = [
    0.001,
    0.001,
    0.001,
]
offset = [
    0.0,
    0.0,
    0.0,
]

[indexed_attributes]
classification = [
    "RangeIndex",
    { SfcIndex = { nr_bins = 16 } },
]
intensity = ["RangeIndex"]
gps_time = ["RangeIndex"]
#TODO

[defaults]
node_hierarchy = 23
point_hierarchy = 15
priority_function = "NrPointsWeightedByTaskAge"
num_threads = 32
cache_size = 10000
compression = true
nr_bogus_points = [
    0,
    0,
]
max_lod = 15
enable_attribute_index = true

[runs.main]