points_file = "../../../data/kitti_sorted.las"
index_folder = "../../../data/kitti-eval"
output_file = "kitti_%d_%i.json"
use_existing_index = false
cooldown_seconds = 0
indexing_timeout_seconds = 50000
target_point_pressure = 1000000
[attributes]
Position3D = "Vec3i32"
Intensity = "U16"
LASBasicFlags = "U8"
Classification = "U8"
ScanAngleRank = "I8"
UserData = "U8"
PointSourceID = "U16"
GpsTime = "F64"
ColorRGB = "Vec3u16"
semantic = "U16"
instance = "U16"
visible = "U8"
confidence = "U16"
# min x y z:                  -2990.515 -3741.836 110.728
# max x y z:                  4090.455 4076.017 290.353

[queries]
full-point-cloud = "full"
lod0 = "lod(0)"
lod1 = "lod(1)"
lod2 = "lod(2)"
classification_ground = "attr(semantic <= 12)"
classification_building = "attr(semantic == 11)"
pointsource1 = "attr(35 <= PointSourceID <= 64)"
pointsource2 = "attr(208 <= PointSourceID <= 248)"
time1 = "attr(199083995.09382153 <= GpsTime <= 466372692.21052635)"
time2 = "attr(687577131.20366132 <= GpsTime <= 805552832.00000000)"
visible = "attr(visible <= 1)"
rgb = "attr(ColorRGB <= [10,10,10])"

[coordinate_system]
scale = [
    0.001,
    0.001,
    0.001,
]
offset = [
    0.0,
    0.0,
    0.0,
]

[indexed_attributes]
semantic = [
    "RangeIndex",
    { SfcIndex = { nr_bins = 16 } },
]
instance = [
    "RangeIndex",
    { SfcIndex = { nr_bins = 16 } },
]
pointsourceid = ["RangeIndex"]
colorrgb = [
    "RangeIndex",
    { SfcIndex = { nr_bins = 16 } },
]

[defaults]
node_hierarchy = 19
point_hierarchy = 11
priority_function = "NrPointsWeightedByTaskAge"
num_threads = 32
cache_size = 500
compression = true
nr_bogus_points = [
    0,
    0,
]
max_lod = 11
enable_attribute_index = true

[runs.main]
compression = [true, false]
enable_attribute_index = [true, false]