points_file = "../../../data/Lille_sorted.las"
index_folder = "../../../data/lille-eval"
output_file = "lille_%d_%i.json"
use_existing_index = false
cooldown_seconds = 0
indexing_timeout_seconds = 50000
target_point_pressure = 1000000
attributes = "LasPointFormat1Raw" # TODO WIRKLICH?

[queries]

[coordinate_system]
scale = [
    0.001,
    0.001,
    0.001,
]
offset = [
    0.0,
    0.0,
    0.0,
]

[indexed_attributes]
classification = [
    "RangeIndex",
    { SfcIndex = { nr_bins = 16 } },
]
intensity = ["RangeIndex"]
gps_time = ["RangeIndex"]
color_rgb = [ #TODO GEHT NICHT
    "RangeIndex",
    { SfcIndex = { nr_bins = 16 } },
]

[defaults]
node_hierarchy = 19
point_hierarchy = 11
priority_function = "NrPointsWeightedByTaskAge"
num_threads = 32
cache_size = 500
compression = true
nr_bogus_points = [
    0,
    0,
]
max_lod = 10
enable_attribute_index = true

[runs.main]