points_file = "../../../data/Lille_sorted.las"
index_folder = "../../../data/lille-eval"
output_file = "lille_%d_%i.json"
cooldown_seconds = 0
indexing_timeout_seconds = 50000
target_point_pressure = 1000000
attributes = "LasPointFormat1Raw"
# min x y z:                  -944.485 -1053.599 16.298
# max x y z:                  67.185 101.894 66.745

[queries]
full-point-cloud = "full"
lod0 = "lod(0)"
lod1 = "lod(1)"
lod2 = "lod(2)"
intensity_high = "attr(Intensity > 128)"
intensity_low = "attr(Intensity <= 2)"
time_1 = "attr(GpsTime > 4983)"
time_2 = "attr(GpsTime < 9158) and attr(GpsTime > 9120)"

[coordinate_system]
scale = [
    0.001,
    0.001,
    0.001,
]
offset = [
    0.0,
    0.0,
    0.0,
]

[indexed_attributes]
intensity = ["RangeIndex"]
gpstime = ["RangeIndex"]

[defaults]
measure_index_speed = true
measure_query_speed = true
measure_query_latency = true
node_hierarchy = 19
point_hierarchy = 11
priority_function = "NrPointsWeightedByTaskAge"
num_threads = 32
cache_size = 500
compression = true
nr_bogus_points = [
    0,
    0,
]
max_lod = 8
enable_attribute_index = true

[runs.main]
compression = [true, false]
enable_attribute_index = [true, false]