data_folder = "data/evaluation"
output_file = "evaluation/results/evaluation_%d_%i.json"
points_file = "data/testdata_histogram_pf3-1000000.las"
trajectory_file = ""
offset = [0,0,0]
las_point_record_format = 3
enable_cooldown = false

[defaults]
type = "Octree"
priority_function = "NrPointsWeightedByTaskAge"
num_threads = 4
cache_size = 4096
node_size = 10000
compression = true
nr_bogus_points = [0, 3000]
insertion_rate.target_point_pressure = 1_000_000
query_perf.enable = true
latency.enable = false
latency.points_per_sec = 20000
latency.frames_per_sec = 5
enable_attribute_index = true
enable_histogram_acceleration = true
bin_count_intensity = 25
bin_count_return_number = 8
bin_count_classification = 256
bin_count_scan_angle_rank = 25
bin_count_user_data = 25
bin_count_point_source_id = 25
bin_count_color = 25

[runs.example]
enable_attribute_index = [true, false]
enable_histogram_acceleration = [true, false]