points_file = "../../../data/AHN4.las"
index_folder = "../../../data/ahn4-eval"
output_file = "../measurements/lidarserv/ahn4_%d_%i.json"
cooldown_seconds = 0
indexing_timeout_seconds = 50000
target_point_pressure = 1000000
attributes = "LasPointFormat1Raw"
# record length 34
#min x y z:                  96750.700 493750.000 -7.079
#max x y z:                  134999.999 512499.999 135.977
# Min GPS Time: 269521185.6002241
#Max GPS Time: 270204590.1666351

[queries]
full-point-cloud = "full"
classification_bridges = "attr(Classification == 26)"
classification_building = "attr(Classification == 6)"
classification_ground = "attr(Classification == 2)"
classification_vegetation = "attr(Classification == 1)"
intensity_high = "attr(Intensity > 1400)"
intensity_low = "attr(Intensity <= 20)"
time_1 = "attr(GpsTime < 270521185)"
time_2 = "attr(270204590 < GpsTime < 270204900)"
time_3 = "attr(269521185 < GpsTime < 269522000)"

[coordinate_system]
scale = [
    0.001,
    0.001,
    0.001,
]
offset = [
    0.0,
    0.0,
    0.0,
]

[indexed_attributes]
classification = [
    "RangeIndex",
    { SfcIndex = { nr_bins = 16 } },
]
intensity = [
    "RangeIndex"
]
gpstime = [
    "RangeIndex"
]

[defaults]
measure_index_speed = false
measure_query_speed = false
measure_query_latency = false
node_hierarchy = 25
point_hierarchy = 17
max_lod = 14
priority_function = "NrPointsWeightedByTaskAge"
num_threads = 32
cache_size = 10000
nr_bogus_points = [
    0,
    0,
]
compression = false
enable_attribute_index = true
enable_point_filtering = true

[runs.insertion-speed]
measure_index_speed = true
compression = [true, false]

[runs.querying]
measure_query_speed = true
enable_point_filtering = ["NodeFilteringWithoutAttributeIndex", "NodeFiltering", "PointFiltering"]

[runs.latency]
measure_query_latency = true

[runs.attr-index]
measure_index_speed = true
measure_query_speed = true
enable_attribute_index = ["All", "RangeIndexOnly", "SfcIndexOnly", "None"]
