points_file = "../../../data/Hamburg.las"
index_folder = "../../../data/hamburg-eval"
output_file = "../results/lidarserv/hamburg_%d_%i.json"
cooldown_seconds = 0
indexing_timeout_seconds = 50000
target_point_pressure = 1000000
attributes = "LasPointFormat7Raw"

[queries]

[coordinate_system]
scale = [
    0.001,
    0.001,
    0.001,
]
offset = [
    0.0,
    0.0,
    0.0,
]

[indexed_attributes]
classification = [
    "RangeIndex",
    { SfcIndex = { nr_bins = 16 } },
]
intensity = ["RangeIndex"]
gpstime = ["RangeIndex"]

[defaults]
measure_index_speed = true
measure_query_speed = true
measure_query_latency = false
node_hierarchy = 23
point_hierarchy = 15
priority_function = "NrPointsWeightedByTaskAge"
num_threads = 32
cache_size = 10000
compression = true
nr_bogus_points = [
    0,
    0,
]
max_lod = 15
enable_attribute_index = true

[runs.main]
compression = [true, false]
enable_attribute_index = [true, false]
enable_point_filtering = [true, false]