points_file = "../../../data/Lille_sorted.las"
index_folder = "../../../data/lille-eval"
output_file = "../measurements/lidarserv/lille_%d_%i.json"
cooldown_seconds = 0
indexing_timeout_seconds = 50000
target_point_pressure = 1000000
attributes = "LasPointFormat1Raw"
# min x y z:                  -944.485 -1053.599 16.298
# max x y z:                  67.185 101.894 66.745

[queries]
full-point-cloud = "full"
intensity_high = "attr(Intensity > 128)"
intensity_low = "attr(Intensity <= 2)"
time_1 = "attr(GpsTime < 20000)"
time_2 = "attr(GpsTime > 23000)"
pointsource1 = "attr(PointSourceID >= 10)"
pointsource2 = "attr(PointSourceID >= 5)"
scananglerank1 = "attr(ScanAngleRank <= 45)"
scananglerank2 = "attr(ScanAngleRank <= 90)"
view_frustum1 = """view_frustum( 
    camera_pos: [-560.45, -584.87, 47.29], 
    camera_dir: [0.75, 0.65, -0.12], 
    camera_up: [0.0, 0.0, 1.0], 
    fov_y: 0.78, 
    z_near: 3.9, 
    z_far: 3994169.6, 
    window_size: [500.0, 500.0], 
    max_distance: 10.0 
)"""

[coordinate_system]
scale = [
    0.001,
    0.001,
    0.001,
]
offset = [
    0.0,
    0.0,
    0.0,
]

[indexed_attributes]
intensity = [
    "RangeIndex",
]
gpstime = [
    "RangeIndex",
]
pointsourceid = [
    "RangeIndex",
]
scananglerank = [
    "RangeIndex",
]

[defaults]
measure_index_speed = false
measure_query_speed = false
measure_query_latency = false
node_hierarchy = 19
point_hierarchy = 11
priority_function = "NrPointsWeightedByTaskAge"
num_threads = 32
cache_size = 500
compression = false
nr_bogus_points = [
    0,
    0,
]
max_lod = 8
enable_attribute_index = true
enable_point_filtering = true

[runs.insertion-speed]
measure_index_speed = true
compression = [true, false]

[runs.querying]
measure_query_speed = true
enable_point_filtering = ["NodeFilteringWithoutAttributeIndex", "NodeFiltering", "PointFiltering"]

[runs.latency]
measure_query_latency = true

[runs.attr-index]
measure_index_speed = true
measure_query_speed = true
enable_attribute_index = ["All", "RangeIndexOnly", "SfcIndexOnly", "None"]
