[package]
name = "point-cloud-viewer"
version = "0.1.0"
authors = ["Tobias Dorra <public.tobias@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pasture-core = "0.1.0"
log = "0.4.14"
ouroboros = "0.9.3"
derivative = "2.2.0"
crossbeam-channel = "0.5.1"

# The multisampling feature needs to blit the depth buffer, which right now is not possible when usaing glium.
# This has been implemented in glium in this pull request: https://github.com/glium/glium/pull/1952
# It is already merged into master, as soon as a new version is published on crates.io,
# we can switch back to an official release.
glium = { git = "https://github.com/glium/glium", rev = "2c6caf96b309a1f31f56e09b74298585ac1928a0" }

[dev-dependencies]
pasture-io = "0.1.0"
dotenv = "0.15.0"
pretty_env_logger = "0.4.0"
pasture-derive = "0.1.0"
las = "0.7.4"