points_file = "../../data/AHN4_66M.laz"
index_folder = "../../data/evaluation"
output_file = "overview_%d_%i.json"
use_existing_index = false
cooldown_seconds = 0
indexing_timeout_seconds = 200
target_point_pressure = 1_000_000
attributes = "LasPointFormat6Raw"

[queries]
lod0 = "lod(0)"
lod1 = "lod(1)"
#lod2 = "lod(2)"
#full-point-cloud = "full"

[coordinate_system]
scale = [
    0.001,
    0.001,
    0.001,
]
offset = [
    0.0,
    0.0,
    0.0,
]

[defaults]
node_hierarchy = 16
point_hierarchy = 9
priority_function = "NrPointsWeightedByTaskAge"
num_threads = 32
cache_size = 10000
compression = false
nr_bogus_points = [0, 0]
max_lod = 10
enable_attribute_index = false

[runs.cache_sizes]
num_threads = [1,2,4,8,16,24,32,40,48,56,64]
compression = [true, false]

[runs.bogus_points]
nr_bogus_points = [
    [0,0],
    [100,0],
    [0,100],
    [100,100],
    [500,0],
    [0,500],
    [500,500],
    [1000,0],
    [0,1000],
    [1000,1000],
    [10000,10000]
]

[runs.priority_functions]
priority_function = [
    "NrPoints",
    "Lod",
    "OldestPoint",
    "NewestPoint",
    "TaskAge",
    "NrPointsWeightedByTaskAge",
    "NrPointsWeightedByOldestPoint",
    "NrPointsWeightedByNegNewestPoint"
]
compression = [true, false]

[runs.n18p11]
node_hierarchy = [18]
point_hierarchy = [10,11,12]

[runs.n17p10]
node_hierarchy = [17]
point_hierarchy = [9,10,11]

[runs.n16p09]
node_hierarchy = [16]
point_hierarchy = [8,9,10]

[runs.n15p08]
node_hierarchy = [15]
point_hierarchy = [7,8,9]

[runs.n14p07]
node_hierarchy = [14]
point_hierarchy = [6,7,8]

[runs.n13p06]
node_hierarchy = [13]
point_hierarchy = [5,6,7]

[runs.n12p05]
node_hierarchy = [12]
point_hierarchy = [4,5,6]

[runs.n11p04]
node_hierarchy = [11]
point_hierarchy = [3,4,5]
