points_file = "../../data/AHN4_138M_sorted.las"
index_folder = "../../data/evaluation"
output_file = "pasture-new_%d_%i.json"
use_existing_index = false
cooldown_seconds = 0
indexing_timeout_seconds = 1800
target_point_pressure = 1_000_000
attributes = "LasPointFormat6Raw"

[queries]
lod0 = "lod(0)"
#lod1 = "lod(1)"
#lod2 = "lod(2)"
full-point-cloud = "full"

[coordinate_system]
scale = [
    0.001,
    0.001,
    0.001,
]
offset = [
    0.0,
    0.0,
    0.0,
]

[defaults]
node_hierarchy = 24
point_hierarchy = 17
priority_function = "NrPointsWeightedByTaskAge"
num_threads = 32
cache_size = 10000
compression = true
nr_bogus_points = [0, 0]
max_lod = 15
enable_attribute_index = false

[runs.example]
